"""update user models

Revision ID: d01ebe7a54c0
Revises: 6ba4a89e515e
Create Date: 2026-09-08 16:13:16.785036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd01ebe7a54c0'
down_revision: Union[str, Sequence[str], None] = '6ba4a89e515e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('streak_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_activity_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_activity_date')
    op.drop_column('users', 'streak_count')
    # ### end Alembic commands ###
